/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dnd.e;

import java.io.IOException;
import java.util.Scanner;

import character.Character;
import character.CharacterController;

public class App {

    public static void main(String[] args) throws IOException {
        Scanner scan = new Scanner(System.in);

        CharacterController cc = new CharacterController();
        Character c = cc.createCharacter(scan);
        System.out.println(c.getCharacterName());

        scan.close();
    }
}
